openfun/warren

.gitlint

Our standard gitlint configuration is missing.

🔧(project) add missing gitlint configuration file

---

CHANGELOG.md
docker-compose.yml
src/backend/core/pyproject.toml
src/backend/core/warren/conf.py
src/backend/core/warren/fields.py
src/backend/core/warren/filters.py
src/backend/core/warren/tests/test_fields.py
src/backend/core/warren/tests/test_filters.py
src/backend/plugins/video/tests/test_api.py
src/backend/plugins/video/warren_video/api.py
src/backend/plugins/video/warren_video/factories.py

As we manipulate time-based data, we need a way to filter queries using date/time ranges. Those filters should be generic and should be injected as a dependency for every route corresponding to an indicator.
One should note that:
1. default time range corresponds to the last seven days,
2. the time range cannot be greater than the API_MAX_TIMESPAN setting.

✨(api) add date/time range filter

---

.circleci/config.yml

Remove ci wrong docker hub publication
The ci was configured to push the app image docker the docker hub under
a wrong name (ralph). I removed these steps and we will add
it back when we decide about which docker images scheme we use
(see https://github.com/openfun/warren/issues/13)
Remove the hub ci job

Backend remove ci wrong docker hub publication job

---

.circleci/config.yml
.env.dist
.gitignore
Makefile
docker-compose.yml

We want warren to query ralph LRS as opposed to directly query the database backend (elasticsearch).
To do so, having ralph in the docker compose would be easier than running both projects locally.
Integrate fundocker/ralph into the docker-compose.yml

🏗️ (project) add Ralph LRS to the development stack

---

src/backend/Dockerfile

`python-dev` has been removed from apt repo and is making the build fail.
The package isn't used in Warren so it does not need to be installed anymore.

🔧(project) remove python-dev from backend Docker image

---

src/backend/core/warren/fields.py

Fix the swagger v1 docs generating an error (/api/v1/docs). The Date and Datetime fields were not declarable with JSON schema
Fix the Date and Datetime pydantic models so that they can be picked up by JSON schema
Manually declare conversion to dict for Date and Datetime

🐛(api) make custom pydantic types Date and Datetime compatible with JSON schema

---

src/backend/core/warren/base_indicator.py
src/backend/core/warren/conf.py
src/backend/core/warren/models.py
src/backend/plugins/video/tests/test_api.py
src/backend/plugins/video/warren_video/api.py
src/backend/plugins/video/warren_video/indicators.py
src/backend/plugins/video/warren_video/models.py

Add `unique` and `complete` endpoint parameters/routes for counting completed video events and/or unique viewers
`/views` with `complete=False`
`/views` with `complete=True`
`/viewers` with `complete=False`
`/viewers` with `complete=True`

✨️(backend) add 2 endpoint parameters

---

src/backend/core/warren/factories/base.py
src/backend/core/warren/tests/test_base_indicator.py

Base indicators was merged before it had tests, in order to limit the size of the PR, and as it already had many discussions. This PR adds the missing tests.
Add unit tests for the `parse_raw_statements` and the `add_actor_unique_id` functions of the `base_indicator.py` file.

(backend) Add base indicator tests

---

bin/pytest

After renaming Docker Compose services, I overlooked updating the bin/pytest bash script to align with the changes.

🩹(api) revamp the neglected backend within `bin/pytest`

---

bin/git-hook-pre-commit

Ensure the hook runs only on staged diffs during partial commits. During a partial commit, a developer may choose to commit only specific changes while leaving other modifications unstaged. The hook should only operate on the staged changes to ensure it does not interfere with uncommitted or unrelated code.

🩹(project) ensure the pre-commit hook runs only on staged diffs 

---

CHANGELOG.md
src/api/plugins/video/tests/test_api.py
src/api/plugins/video/warren_video/api.py
src/api/plugins/video/warren_video/indicators.py

The video identifier is an IRI that can be a UUID in the form of an IRI, but it’s not a UUID. This corrects video’s semantic representation and avoids any potential confusion caused by misleading naming.

♻️(api) rename video uuid to match xAPI semantic

---

CHANGELOG.md
src/api/core/warren/models.py
src/api/plugins/video/tests/test_api.py
src/api/plugins/video/warren_video/indicators.py
src/frontend/packages/ui/video/Views.tsx
src/frontend/packages/ui/video/types/index.ts

Optimize code readability, by avoiding redundant info and use concise names in indicators
Note: `count_by_date` temporary vars in all `compute` methods haven't been renamed on purpose. These will change with #47.

♻️(api) use concise names in indicators and models

---

CHANGELOG.md
src/api/core/warren/models.py
src/api/plugins/video/tests/test_api.py
src/api/plugins/video/warren_video/indicators.py

The API should return a count of 0 if there were no events on a given date.
This fix is inspired by @jmaupetit previous works on the API, you could find [here](https://github.com/openfun/warren/blob/e1b60d5d0f4a35ce482872d2d3c62ba35deed49a/src/backend/plugins/video/warren_video/api.py).
During the indicator computation, it is essential to initialize the DailyCounts with a count of zero for each date within the expected date range. Subsequently, the counts should be updated with the appropriate values. This approach guarantees that each date will have a returned value, and the dates will be sorted accordingly.

🐛(api) return a count of 0 if there were no events

---

renovate.json

The `ignoreDeps` configuration field allows you to define a list of dependency names to be ignored by Renovate. However, it supports only exact match dependency. As `ipython` and `pytest-httpx` are dev dependencies, renovate bot seems to prefix them with `dev/`. This fixes their ignored dependency names.

🩹(renovate) prefix ignored dev dependencies with `dev/`

---

src/frontend/apps/web/package.json
src/frontend/package.json
src/frontend/packages/ui/package.json
src/frontend/yarn.lock

To ensure absolute certainty and clear visibility of the dependencies being used, all dependencies have been pinned to their currently installed versions. This approach empowers developers with precise knowledge about the exact versions of each dependency that are in use at any given time.
For detailed insights into the advantages of employing pinned dependencies, please refer to the documentation provided by Renovate: [Dependency Pinning in Renovate](https://docs.renovatebot.com/dependency-pinning).
Special thanks to @jbpenrath for their suggestion.
As part of this proposal, updates were applied to three `package.json` files:

📌(frontend) pin all dependencies being used to ensure certainty and clear visibility 

---

src/api/core/warren/models.py
src/api/plugins/video/tests/test_api.py
src/api/plugins/video/warren_video/api.py
src/frontend/packages/ui/video/api/getVideoViews.ts

Use the default `HttpException` from `fastAPI` to enhance our API's error handling capabilities.
Integrated the default HttpException to enhance our API's error handling capabilities. The HttpException behaves like a standard Python exception with additional data relevant for APIs.
When this exception is raised, it effectively prevents the further execution of the API call. We unlock the potential for more advanced configuration options during exception handling.
Moreover, this approach eliminates the need for custom Pydantic models dedicated to managing API responses, leading to a  more maintainable code.

🩹(api) fix client error handling with HttpException

---

src/app/apps/lti/templates/config.xml
src/app/apps/lti/urls.py
src/app/apps/lti/views.py
src/app/warren/settings.py

This update offers for LTI consumers to access Warren's LTI configurations via a designated URL. The endpoint returns a set of predefined LTI parameters that can be customized as necessary when establishing the LTI connection within an LMS.
Please be aware that the URL for the icon might require updating once Warren obtains a logo.

✨(app) enable consumer access to LTI Provider Configurations

---

.gitignore
Makefile
docker-compose.yml
src/api/core/warren/conf.py
src/app/apps/dashboards/templates/dashboards/base.html
src/app/apps/dashboards/views.py
src/app/warren/settings.py
src/frontend/apps/web/index.html
src/frontend/apps/web/package.json
src/frontend/apps/web/src/App.tsx
src/frontend/apps/web/src/main.tsx
src/frontend/apps/web/src/utils.ts
src/frontend/apps/web/vite.config.ts

Integrate the Web app using the Django LTI server for rendering.
This has been influenced by Marsha's approach, but please keep in mind that this implementation is not yet finalized. Our upcoming plans involve substantial code refactoring to incorporate app routing and refine the initialization logic.
Running `make run` would start the development server, namely the Django app. Then, you could access the frontend through two paths:
- The dashboard navigating through `http://localhost:8090/dashboards/`
- The development interface refined by @jmaupetit navigating through `http://localhost:8090/develoment/`.
In the upcoming iterations, we aspire to set up the frontend app initialization process and content loading. Our app's capabilities, while limited, will allow users to:
- Select specific …

✨(frontend) Basic LTI rendering 

---

.circleci/config.yml

We now build and distribute two Docker images to run Warren. Let's automate build checking and publication!

👷(circle) add backend images build and publication

---

.circleci/config.yml
src/api/core/pyproject.toml
src/app/pyproject.toml

Check for print statements in the `make lint` command instead of the `lint-git` job.
The `lint-git` CI job might not be the optimal location for examining print statements, as this is more aligned with the responsibility of our linter. Moreover, the inspection of print statements is language-specific and should pertain only to jobs running on Python files. `lint-git` is running both on python and JavaScript files.

👷(ci) harmonize CI linting rules with local development guidelines

---

src/api/core/warren/exceptions.py
src/api/plugins/video/warren_video/api.py
src/api/plugins/video/warren_video/indicators.py

LRS client exceptions were not being handled correctly, resulting in API server failures.
To fix this issue, we created a custom `ClientException` class, and implement error handling for it in all API routes responsible for computing indicators by fetching statements.

🥅 (api) catch BackendException from the LRS client

---

src/api/core/warren/filters.py
src/api/plugins/video/warren_video/api.py

`HTTPException` statuses were previously hard-coded with integer values. Importing Fast API constants, we not only enhance the maintainability of this logic, but also provide explicit names for each status code. Under the hood, These constants are imported from the `starlette` package. Please find all constants [here](https://github.com/encode/starlette/blob/master/starlette/status.py)

🎨(api) import FastAPI HTTP status constants to avoid hardcoding integer values

---

src/app/apps/lti/tests/test_lti_select.py
src/app/apps/lti/views.py

Limit the Content-Item Selection view to a user with a `read-write-configure` role, e.g. `instructor` or `admin`. 
For example, a `student` does not have permissions to select content through deep-linking, but they can render selected content. 
It closes #89.

🛂(app) limit deep-linking access to 'read-write-configure' LTI role

---

.circleci/config.yml
Makefile
docker-compose.yml
src/api/Dockerfile

All docker images required to run Warren will be called `warren` and we distinguish application services by their image tag.
- `warren:app-latest` is the latest warren app service
- `warren:api-core-latest` is the latest warren api service (core version)
- `warren:api-full-latest` is the latest warren api service (full version, i.e. with all official plugins installed)
`latest` points to the latest release, but each version tag will also be published (e.g. `warren:app-0.1.0`, `warren:api-core-0.1.0`, `warren:api-full-0.1.0`).
Docker images repository: https://hub.docker.com/repository/docker/fundocker/warren/general

👷(circle) move to a single docker image name

---

src/api/plugins/video/tests/test_indicators.py
src/api/plugins/video/warren_video/indicators.py

Added a missing check while constructing subclasses of `BaseDailyEvent`.
Improved the documentation on declaring new indicators that inherit from `BaseDailyEvent`.
These two additions should enhance the DX while using `BaseDailyEvent`.

🧑‍💻(api) enforce the declaration of 'verb_id' in all video indicators

---

src/api/core/warren/filters.py
src/api/core/warren/tests/test_filters.py
src/api/core/warren/tests/test_xapi.py
src/api/core/warren/xapi.py
src/api/plugins/video/tests/test_api.py
src/api/plugins/video/tests/test_indicators.py
src/api/plugins/video/warren_video/indicators.py
src/frontend/packages/ui/video/utils.ts

Ensure consistent timezone in DailyEvent indicators

---

README.md

With LTI, frontend rendering is available on a different URL. README did not
mention it.
Update README.md to inform user to access rendering at
http://localhost:8090/development.

📝(project) update README.md

---

src/api/core/warren/db.py
src/api/core/warren/indicators/__init__.py
src/api/core/warren/indicators/base.py
src/api/core/warren/indicators/mixins.py
src/api/core/warren/models.py
src/api/core/warren/tests/conftest.py
src/api/core/warren/tests/fixtures/db.py
src/api/core/warren/tests/test_indicators_base.py
src/api/core/warren/tests/test_indicators_mixins.py
src/api/core/warren/tests/test_models.py
src/api/core/warren/tests/test_xapi.py
src/api/core/warren/xapi.py
src/api/plugins/video/tests/conftest.py
src/api/plugins/video/tests/test_api.py
src/api/plugins/video/tests/test_indicators.py
src/api/plugins/video/warren_video/api.py
src/api/plugins/video/warren_video/indicators.py

We need to make video indicators cachable.
During this work, we've also decided to make indicators' usage more straightforward. There should be one obvious way to perform a calculation: using a single indicator instance. Maybe this immutability criterion should be enforced even further in a near future.

Cache video indicators

---

.circleci/config.yml
.gitignore
Makefile
src/app/Dockerfile
src/app/apps/lti/templates/base.html
src/frontend/apps/web/vite.config.ts

Warren `app` service requires the frontend build to work, and it is not bundled in the `warren:app` Docker image.
Frontend application build is now a requirement to build the `app` service Docker image.

📦️(app) bundle the frontend app build in the staticfiles

---

src/api/plugins/video/tests/test_api.py
src/api/plugins/video/warren_video/indicators.py

Views is computed by counting `played` events generated before a threshold
on the video timeline.
Currently, indicators based on views computation was counting events generated
after this threshold. It has been reversed and tests adapted.

🐛(api) fix views computation

---

.circleci/config.yml

The `hub` CI job is responsible to publish Docker images to DockerHub. It seems broken since recent changes to the way we build the app production image.

Fix CI Hub job

---

src/app/apps/lti/tests/test_lti_config.py
src/app/apps/lti/tests/test_lti_request.py
src/app/apps/lti/tests/test_lti_select.py
src/app/pyproject.toml
src/app/warren/settings.py

[Whitenoise](https://whitenoise.readthedocs.io/en/latest/django.html) help serving static files of a Django project. By using this app, we no longer need to serve them with Nginx or alike.

➕(app) add whitenoise to serve static files

---

src/api/plugins/video/tests/test_api.py
src/api/plugins/video/tests/test_indicators.py
src/api/plugins/video/warren_video/indicators.py

Views indicators tests pass for all requested `played` statements.
It has been designed that normally such indicators should only compute on
`played` statements that were generated in the 30 first seconds of a video. 
The mixin used for DailyViews was placed after the DailyEvent class in
inheritance, causing method resolution order issues. By reordering the
inheritance sequence, indicators now correctly inherit methods from the mixin.

🐛(indicators) fix method inheritance order for views indicators

---

src/api/core/pyproject.toml
src/app/pyproject.toml

Coverage measurement is applied on different packages levels, however tests
files are included in the package files. Coverage reporting mentions coverage of
test files which makes non sense.
The `.coveragerc` file allows to custom the coverage configuration and provides
filenames pattern to ignore when coverage measurement is run.
- https://pytest-cov.readthedocs.io/en/latest/config.html
- https://coverage.readthedocs.io/en/latest/config.html#run-omit

🔧(project) ignore `tests` subfolders for coverage measurement

---

src/api/core/warren/api/__init__.py
src/api/core/warren/api/health.py
src/api/core/warren/db.py
src/api/core/warren/tests/test_api_health.py
src/api/core/warren/tests/test_db.py

When deploying an application in production (e.g. in a Kubernetes environment), we need a way to check its status so that we can restart it if required.
We've implemented [Mozilla's Dockerflow](https://github.com/mozilla-services/Dockerflow) endpoints.

✨(api) add health check endpoints

---

docker-compose.yml
src/api/Dockerfile
src/api/core/logging-config.dev.yaml
src/api/core/logging-config.prod.yaml

Offer developers to access debug logs while developing.
Replaced '--log-level' option with dedicated configs for development and production. Previously, setting logging levels affected only uvicorn logs, not custom loggers. Now, two distinct files manage logging. One for each environment.

🩹(api) redefine API logging configuration

---

src/app/warren/settings.py
src/frontend/apps/web/vite.config.ts

Fix rendering in the pre-production demo on moodle.
Disabled manifest generation in Django Whitenoise and turned off output compression in Vite Rollup configuration. This ensures that each tool focuses on its specific responsibilities.
Whitenoise's file hashing was conflicting with Vite's code splitting. Vite's unique chunk filenames make Whitenoise's cache sufficient for handling.

🚑️(frontend) fix static files serving

---

src/api/Dockerfile
src/app/Dockerfile

Development stack has been recently upgraded to Python 3.12.
However, warren image builds takes more than 10 minutes because of wheels for
pandas package that are not available for pandas 2.0.3. (that we have pinned
as the latest release supporting Python 3.8).
Rollback Python dev release to Python 3.11

⏪️(project) downgrade Python release for development stack

---

src/api/core/warren/api/__init__.py
src/api/core/warren/db.py
src/api/core/warren/indicators/mixins.py

We've observed connection issues to the PostgreSQL server when many requests are send in parallel.
Use the singleton pattern to avoid opening too many connections to the database and reach the maximal connection pool for database requests during API heavy load.

🐛(api) force single database engine and session per thread

---

.circleci/config.yml
CHANGELOG.md
renovate.json
src/api/Dockerfile
src/api/core/pyproject.toml
src/api/plugins/video/pyproject.toml
src/app/Dockerfile
src/app/pyproject.toml

Python v3.8 is deprecated in one year, and no longer a requirement for Warren.
Please note that `ralph-malph` v3.9 is still blocking `pytest-httpx` and `httpx` dependencies to their actual pinned versions.

🔧(backend) deprecate support for Python v3.8

---

renovate.json

Make renovate ignores Django
Renovate runs an exact match on deps.

🩹(api) fix capitalization issue for Django pinned renovate dependency

---

src/api/core/pyproject.toml

Development dependencies need a clean up.
Factory boy is not used at all. We choose Polyfactory.
Faker is second degree dependency of Polyfactory. There is no need to pin or handle it as first degree dependency.

➖(api) remove unused factory-boy and faker

---

bin/seed_experience_index.py

The function now returns a classic value. This was not considered in the recent rebase of the branch.

🐛(api) fix seeding the Experience Index

---

src/api/Dockerfile

Production images are distributed with application sources (copied in the `/app` directory), but it's not required to run the application as warren core and plugins are installed in the installed Python's distribution.
As a side effect, the core Docker image was embedded along with all official plugins, not only core sources.

🚀(api) remove useless sources from docker images

---

bin/alembic
src/api/core/pyproject.toml
src/api/core/warren/alembic.ini
src/api/core/warren/commands.py
src/api/core/warren/migrations/__init__.py
src/api/core/warren/tests/fixtures/db.py
src/api/core/warren/tests/test_commands.py

When installing Warren API python package, one need to be able to run database-related operations (migrations) using alembic. As alembic requires a per-project configuration, we need to distribute alembic configuration in the API core python package, and provide a wrapper script that runs alembic behind the scene.

Distribute API database migrations

---

src/api/Dockerfile

Docker image build for development is broken:
```
=> ERROR [development 2/2] RUN pip install -e ./core[dev] &&     for plu  0.9s
------
> [development 2/2] RUN pip install -e ./core[dev] &&     for plugin in ./plugins/*; do         pip install -e "${plugin}[dev]";     done:
#0 0.764 Obtaining file:///app/core
#0 0.765 ERROR: file:///app/core does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
------
failed to solve: process "/bin/bash -o pipefail -c pip install -e ./core[dev] &&     for plugin in ./plugins/*; do         pip install -e \"${plugin}[dev]\";     done" did not complete successfully: exit code: 1
```
We introduced this regression in #173.

🐛(api) fix docker development image

---

bin/seed_experience_index.py

When bootstraping the project, experience index seeding fails:
```
Seeding the experience index…
Traceback (most recent call last):
File "/opt/src/seed_experience_index.py", line 11, in <module>
from warren.xi.models import (
ImportError: cannot import name 'Experience' from 'warren.xi.models' (/app/core/warren/xi/models.py). Did you mean: 'ExperienceRead'?
```
We recently refactored the `xi` application models for Pydantic and SQLModel and forgot to adapt the seeding script.

🐛(api) fix XI seeding script

---

src/api/core/warren/commands.py
src/api/core/warren/tests/test_commands.py

With the program name passed as the first argument from sys.argv, the argument parser does not validate the command.

🐛(api) fix warren command line parser

---

docs/Dockerfile

MacOS users default group ID is `20` (staff). This group often already exists on GNU/Linux distributions, hence we should not enforce its creation if it already exists, or else the `docs` Docker image build fails.
Make group creation optional.

🐛(docs) fix Docker image build for MacOS users

---

Makefile

Allow developer cleaning their repo, by restoring it as it was freshly cloned. Especially useful to solve recurrent out-dated env files.

🧑‍💻(project) introduce a clean command

---

bin/warren
src/api/core/warren/cli.py
src/api/core/warren/tests/test_cli.py
src/api/plugins/video/pyproject.toml

We need a way to batch pre-calculate indicators from the CLI (as cronjobs for example).
The `indicator` command and its sub-commands allow to perform indicators calculations from the CLI.
It ships with 3 sub-commands:
- `list`: list indicators registered for batch computing using the CLI
- `inspect`: show expected indicator arguments required to run
- `compute`: compute the indicator given input arguments and optionally cache the result
TODO:

🔨(api) add Warren CLI `indicator` command (and sub-commands)

---

.circleci/config.yml
Makefile
docker-compose.yml
docs/contribute.md
docs/index.md
docs/plugins.md
mkdocs.yml

The recently introduced `warren indicator` CLI command supposes plugins to be properly declared. We need to start documenting API plugins guidelines.

Add plugins documentation

---

.circleci/config.yml

CircleCI is deprecating all ubuntu machines to ensure pipelines run on latest versions.
Changing ubuntu machines to `default` (latest stable version). Refer to https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177

💚(circle) change deprecated ubuntu machines

---

src/api/core/warren/cli.py
src/api/core/warren/tests/test_cli.py
src/api/core/warren/tests/xi/indexers/moodle/test_client.py
src/api/core/warren/xi/client.py
src/api/core/warren/xi/indexers/exceptions.py
src/api/core/warren/xi/indexers/moodle/client.py

We need a CLI command to (list and) index Moodle courses and content in the Experience Index.

Add XI CLI commands

---

src/api/core/pyproject.toml
src/api/core/warren/tests/conftest.py
src/api/core/warren/tests/fixtures/app.py
src/api/core/warren/tests/fixtures/auth.py
src/api/core/warren/tests/test_utils.py
src/api/core/warren/tests/xi/client/test_crud_experience.py
src/api/core/warren/tests/xi/client/test_crud_relation.py
src/api/core/warren/tests/xi/routers/test_experiences.py
src/api/core/warren/tests/xi/routers/test_relations.py
src/api/core/warren/utils.py
src/api/core/warren/xi/client.py
src/api/core/warren/xi/routers/experiences.py
src/api/core/warren/xi/routers/relations.py

The Experience Index is not supposed to get required with no prior authentication.

🔒️(api) require authentication for xi requests

---

src/api/core/warren/indicators/mixins.py
src/api/core/warren/tests/indicators/test_mixins.py

We cannot save complex indicators' result as SQLAlchemy is not able to JSON serialize them before saving.
When using complex embedded Pydantic models for indicator results, we need to serialize them before they can be saved in the database's Cache.

🐛(api) serialize complex models before saving them

---

src/api/core/warren/conf.py
src/api/core/warren/migrations/__init__.py
src/api/core/warren/tests/fixtures/db.py

Alembic config file is embedded in Warren lib packaging, however, it needs a
relative path to be accessed. Otherwise a redefinition is necessary.
Add a `ROOT_PATH` setting variable for alembic config file relative path
location.

♻️(api) configure root path global variable for alembic configuration

---

src/frontend/packages/core/.eslintignore
src/frontend/packages/core/package.json
src/frontend/packages/core/tsup.config.ts
src/frontend/packages/video/.eslintignore
src/frontend/packages/video/package.json
src/frontend/packages/video/tsup.config.ts
src/frontend/yarn.lock

We need to embed Scss compiled styles to frontend packages so that all components can benefit from them.

🐛(frontend) add missing CSS files in packages

---

src/frontend/packages/core/CHANGELOG.md
src/frontend/packages/core/package.json
src/frontend/packages/video/CHANGELOG.md
src/frontend/packages/video/package.json

- Fix CSS files missing in distributed package

🔖(frontend:patch) bump core release to 0.1.1

---

src/api/core/pyproject.toml
src/app/pyproject.toml

Some options of ruff configurations have been moved under `lint` sections.
The `pyproject.toml` config is adapted to stop raising warnings concerning this
relocation.
See Ruff settings documentation: https://docs.astral.sh/ruff/settings/

🔧(project) fix ruff linter warning

---

docker-compose.yml

The warning `WARN[0000] docker-compose.yml: `version` is obsolete` is displayed.
The `version` is deprecated and not used anymore by the latest Compose file format 1.27.0+.
Removing the field.
_Note_: A discussion about it here https://github.com/openfun/joanie/pull/721/files#r1547736981

🔥(project) remove obsolete docker compose version

---

src/app/apps/development/views.py

After one refresh, development view returns an error. As we are not copying the
LTI_PARAMETERS dict but simply refering to the object, the LTI_PARAMETERS dict
is also modified, resulting in a different initialization on the next refresh.
Fixing it by copying the dict instead of refering to it.

🔨(project) fix development view error after a refresh

---

CHANGELOG.md
src/frontend/packages/core/src/components/BreadCrumb/index.tsx

Previously, the order of the breadcrumb trail was ambiguous, displaying:
organization > session > course
Addressing the issue by rearranging it to:
organization > course > session

🐛(frontend) correct breadcrumb trail order

---

CHANGELOG.md
src/app/apps/lti/tests/test_lti_request.py
src/app/apps/lti/views.py
src/frontend/packages/core/src/types/index.ts

With the latest release of `django-lti-toolbox` (version 1.3.0), we can now add the course id in the app data, passed from the Django view to the frontend.
It will allow us to build dashboards restricted to a particular course.

✨(app) send course id to the frontend

---

src/frontend/.changeset/shaggy-cats-wait.md
src/frontend/packages/core/package.json
src/frontend/packages/video/package.json

The types were missing in all packages build. To fix this issue, the build command in each package.json is modified to specify for the  --dts option the entry to use
See: https://tsup.egoist.dev/#generate-declaration-file

🐛(front/packages) export types in build package

---

src/frontend/.changeset/stupid-mice-clap.md
src/frontend/packages/core/package.json
src/frontend/packages/core/src/components/BoundaryScreenError/_index.scss
src/frontend/packages/core/src/components/BoundaryScreenError/index.tsx
src/frontend/packages/core/src/components/LTI/AppContentLoader/index.tsx
src/frontend/packages/core/src/index.scss

Adding an error boundary component that wraps the app content and prevent any errors within that content to cause the entire application to crash.
Instead, it will catch those errors, and display an error message.
This is particularly beneficial in scenarios where no course id has been passed through the LTI context.

✨(frontend) add an error boundary wrapper component

---

src/api/core/warren/migrations/__init__.py
src/api/core/warren/migrations/env.py
src/api/core/warren/tests/api/test_health.py
src/api/core/warren/tests/fixtures/db.py
src/api/core/warren/tests/test_db.py

Tests were using the `warren-api` database instead of the test database `test-warren-api`, forcing dev to create the real database.

✅(api) use test database in tests

---

CHANGELOG.md
src/api/core/warren/indicators/mixins.py
src/api/core/warren/tests/indicators/test_mixins.py

As of now, an indicator may return different results for the same LRS query (for example with a boolean flag passed as an attribute, or an env setting), we cannot use the cache mixins, as we only rely on the LRS query as a cache key.
Changing it for a hash from its instance attributes, so cache mixins are usable for these indicators.

✨(api) change cache key to instance attributes

---

Makefile
bin/warren

In PR #249, the default database URL was removed from the Alembic configuration file to facilitate testing with the test database without performing any migrations on the real database.
However, this change prevented migrations from being executed when using the Alembic binary, causing the bootstrap makefile rule to fail.
Adding the possibility to execute migrations when warren-api is not running.

🔨(api) make migrations with warren cli

---

CHANGELOG.md
src/api/core/warren/cli.py
src/api/core/warren/migrations/__init__.py
src/api/core/warren/tests/test_cli.py

The Warren CLI Alembic wrapper lacked a command to verify if the database has any unapplied migrations.                                                       
This update introduces a migration check command, which will exit with a status of 1 if there are unapplied migrations in the target database.

✨(cli) add migration check command

---

.circleci/config.yml

When generating a versioned documentation locally and preparing for push, mike was encountering an error due to the absence of the --update-aliases option.
Adding the option, ensuring that the latest alias can be correctly updated to the latest version.

💚(circle) fix issue with mike documentation build

---

CHANGELOG.md
src/api/core/warren/models.py
src/api/core/warren/tests/test_utils.py
src/api/core/warren/utils.py
src/api/core/warren/xi/client.py
src/app/apps/lti/forms.py
src/app/apps/lti/tests/test_lti_request.py
src/app/apps/lti/tests/test_lti_select.py
src/app/apps/lti/tests/test_token.py
src/app/apps/lti/token.py
src/app/apps/lti/views.py

Previously, `course_id` was transmitted to the frontend through app context data.
`user_id` was not transmitted to the frontend.
To be secure, both `course_id` and `user_id` will now be transmitted through the LTI token instead of the app context data.
This change prevents users from altering the course_id or user_id to access unauthorized data.

🔒️(project) securely pass user and course ids through jwt

---

CHANGELOG.md
src/api/core/warren/__init__.py
src/app/version.json
src/app/warren/__init__.py

Added:
- Add dedicated views depending on LTI roles
Changed:
- Remove restricted access to instructors and administrators

🔖(minor) prepare 0.3.0 distribution release

---

docker-compose.yml
src/api/core/pyproject.toml

By default, Elasticsearch sets disk watermark values as percentages of
available disk space. For developers working locally, this can results in
insufficient disk space to run the Elasticsearch container.
To address this, setting the low and high watermark limits to absolute values.

🔧(project) set absolute disk watermark limits for elasticsearch

---

src/frontend/packages/core/package.json
src/frontend/packages/core/src/components/LTI/AppContentLoader/index.tsx
src/frontend/packages/core/src/contexts/index.ts
src/frontend/packages/core/src/contexts/jwtContext.tsx
src/frontend/packages/core/src/hooks/index.ts
src/frontend/packages/core/src/hooks/useJwtContext.ts
src/frontend/packages/core/src/hooks/useRefreshToken.ts
src/frontend/packages/core/src/provider/app.tsx
src/frontend/packages/core/src/types/index.ts
src/frontend/packages/core/src/utils/decodeJwtLTI.ts
src/frontend/packages/core/src/utils/index.ts
src/frontend/packages/core/src/utils/jwtDecode.ts

Jwt token contains course and user information, that can be accessed after
decoding the token. As a decoding step is time consuming, it is executed once
and the content is available for the whole app.
`decodeJwtLTI` utils is now available in warren-core to decode the JWT token and
use `course_id`, `user` or user `roles` everywhere in the application.

Decode and store JWT token in frontend

---

src/frontend/.changeset/stupid-mice-clap.md
src/frontend/packages/core/CHANGELOG.md
src/frontend/packages/core/package.json

Minor Changes
- Add a context to pass data of decoded jwt through the app components
- Add an error boundary wrapper component

🔖(frontend:minor) bump core release to 0.3.0

---

docs/tdbp.md
mkdocs.yml

To provide future users of the Warren-TdBP SaaS with the necessary documentation to configure their Moodle instance.
Add detailed documentation for Warren-TdBP SaaS users to the Warren documentation page.

📝(project) add documentation for setting up warren-tdbp service

---

CHANGELOG.md
src/api/core/pyproject.toml
src/app/apps/lti/tests/test_lti_request.py
src/app/pyproject.toml

- `django-lti-toolbox` version 2.0.0 rely on the consumer URL instead of the HTTP_REFERER to build the `origin_url`.
It will allow us to have LMS instances under subpath, e.g. `https://lms.example.com/moodle/`\.
- The same URL was used for both the consumer and Warren in tests. Changing it to make it more clear.

⬆️(project) upgrade django-lti-toolbox to 2.0.0

---

CHANGELOG.md
src/api/core/warren/__init__.py
src/app/version.json
src/app/warren/__init__.py

- Upgrade `django-lti-toolbox` to 2.0.0 to be compatible with Moodle instances under a subpath

🔖(minor) prepare 0.4.0 distribution release

---

.gitignore
docker-compose.yml
src/api/.dockerignore
src/api/core/warren/conf.py
src/api/core/warren/tests/conftest.py
src/api/core/warren/tests/test_fields.py
src/api/core/warren/tests/test_filters.py
src/api/plugins/video/tests/conftest.py
src/app/apps/development/views.py
src/app/apps/lti/tests/test_lti_config.py

ruff has replaced pylint in project's linter however some pieces of configs and
escapes remained.
- remove useless pylint escapes
- remove pylint env variable in docker compose
- remove untracking of pylint files for git and docker

Clean project from remaining pylint config and escapes
