openfun/warren

- .circleci/config.yml
- .env.dist
- .gitignore
- CHANGELOG.md
- Makefile
- bin/pytest
- docker-compose.yml
- src/backend/.pylintrc
- src/backend/pyproject.toml
- src/backend/tests/api/v1/test_video.py
- src/backend/tests/conftest.py
- src/backend/tests/fixtures/app.py
- src/backend/tests/fixtures/backends.py
- src/backend/tests/test_api.py
- src/backend/warren/api/__init__.py
- src/backend/warren/api/v1/__init__.py
- src/backend/warren/api/v1/video/__init__.py
- src/backend/warren/backends.py
- src/backend/warren/conf.py
- src/backend/warren/factories/__init__.py
- src/backend/warren/factories/base.py
- src/backend/warren/factories/video.py
- src/backend/warren/fields.py
The first (easiest) indicator we choose to implement is a video views endpoint.
To be able to version our API, the root app mounts apps from different versions. Starting with v1, we now connect to an Elasticsearch cluster and add support for video views calculation.
An example request would look like:
```
curl "http://localhost:8100/api/v1/video/{video_id}/views"
```
with `{video_id}` corresponding to the URL encoded video IRI, _e.g._:
```
curl "http://localhost:8100/api/v1/video/uuid%3A%2F%2F8d386f48-3baa-4acf-8a46-0f2be4ae243e/views"
```
The (truncated) response would look like:
```json
{
"total": 73,
"daily_views": [
{
"day": "2023-02-08",
"views": 1
},
{
"day": "2023-02-09",
"views": 3
},
{
"day": "2023-03-07",
"views": 4
}
]
}
```
> Add video views API

- docker-compose.yml
Maintain consistency across different environments and reduce the risk of unexpected changes or bugs introduced by newer versions of Ralph.
> 🩹(api) pin Ralph docker image

- src/api/plugins/video/tests/test_api.py
The recently merged indicators are lacking some unit tests. This PR adds one of them, and allowed to discover a potential issue in our implementation, see the comment on the PR.
Add a test for the video views endpoint, with the parameter `unique=True`.
> ✅(backend) add unique views indicator test

- renovate.json
We need a way to check/list updates statuses. We are currently blind. Nothing happens. We don't know why.
We tried to activate the Dependency dashboard as stated in Renovate's documentation.
Reference: https://docs.renovatebot.com/key-concepts/dashboard/
> 🔧(project) activate renovate dashboard

- CHANGELOG.md
- src/api/core/pyproject.toml
- src/api/plugins/video/pyproject.toml
- src/app/pyproject.toml
Provide clear requirements on Python version.
Align pyproject.toml `requires-python` values with their classifiers and the built images in the CI.
> 🩹 align Python version requirements for the api and the App

- CHANGELOG.md
- src/api/core/warren/base_indicator.py
- src/api/core/warren/tests/test_base_indicator.py
- src/api/plugins/video/warren_video/api.py
- src/api/plugins/video/warren_video/indicators.py
Reduce code's duplication between video's indicators.
Abstract the views and downloads indicators into a more modular general indicator.
> ♻️(api) factorize video's indicators

- src/app/apps/lti/tests.py
- src/app/apps/lti/tests/test_lti_config.py
- src/app/apps/lti/tests/test_lti_request.py
- src/app/apps/lti/tests/test_lti_respond.py
- src/app/apps/lti/tests/test_lti_select.py
- src/app/apps/lti/views.py
- src/app/pyproject.toml
Ensure that the LTI code functions correctly and as expected.
Add tests on each view responsible for an LTI function.
> Add test in LTI functions

- src/api/core/warren/models.py
- src/api/core/warren/tests/test_models.py
Enhance both code readability and developer experience by testing these Pydantic models.
Following @quitterie-lcs's suggestions, add tests and examples. It closes #95
> ✅ add test on count models

- Makefile
- docker-compose.yml
- notebook/Dockerfile
- notebook/notebooks/2023-09-20-al-explore-moodle-data.md
- notebook/notebooks/benchmark_aggregation.md
Explore statements extracted from a Moodle instance
Create a first draft, of an EDA notebook. I used Plotly to make interactive plot.
Please unzip the dataset, and move the Json file to the `data`folder.
https://github.com/openfun/warren/assets/45729124/9c039cb5-ec66-4334-8b6b-ea326297c3c3
> ⚗️(notebook) explore statements extracted from Moodle 

- src/frontend/apps/web/components/AppContentLoader/index.tsx
- src/frontend/packages/ui/components/LoadingBarWrapper/index.tsx
- src/frontend/packages/ui/video/api/getVideoViews.ts
- src/frontend/packages/ui/video/components/Metrics/ViewsMetric.tsx
Enhance the UX while loading the dashboard.
https://github.com/openfun/warren/assets/45729124/0f53efb6-b892-496d-ab4f-b4cc529dba25
> ♻️(frontend) improve networking operations

- docker-compose.yml
- src/api/core/logging-config.yaml
- src/api/core/warren/conf.py
- src/api/core/warren/indicators/models.py
- src/api/core/warren/models.py
- src/api/core/warren/tests/test_fields.py
- src/api/core/warren/tests/test_indicators_models.py
- src/api/plugins/video/warren_video/api.py
- src/api/plugins/video/warren_video/indicators.py
- src/app/warren/settings.py
Optimize logging levels for improved clarity and efficiency.
> 🔊 (api) enhance logging strategy

- src/frontend/apps/web/package.json
- src/frontend/packages/ui/package.json
- src/frontend/packages/ui/video/components/Filters/index.tsx
- src/frontend/yarn.lock
Resolve layout inconsistencies related to the Select filter's growing height.
Added the 'monoline' props to the Select video filters.
https://github.com/openfun/warren/assets/45729124/9fac8a28-5f62-4377-98f2-89ed710aed83
> ✨ Make Select video filters monoline

- src/api/core/warren/xi/routers/experiences.py
- src/api/core/warren/xi/routers/relations.py
Refined exception handling in experience index routers, by narrowing try-except scopes.
> 🥅(api) scope try-except block for Experience or Relation Creation

- Makefile
- bin/seed_experience_index.py
- docker-compose.yml
Populate frontend from the Experience Index.
Seed the experience index while bootstrapping the project with mocked data.
> 🚧(api) seed the experience index on bootstrap

- .circleci/config.yml
- Makefile
- docker-compose.yml
- docs/Dockerfile
- docs/contribute.md
As we only have a single documentation version for now, we need to set the default version to point to.
> WIP: fix documentation build with mike

- .circleci/config.yml
- bin/changeset
- docs/contribute.md
Each service should be released separately and globally.
> Add per-service release support

- src/frontend/.changeset/wicked-beans-watch.md
- src/frontend/packages/core/CHANGELOG.md
- src/frontend/packages/core/package.json
> Prepare @openfun/warren-core 0.1.0 release

- .circleci/config.yml
NPM packages publication using `changeset` failed on the first run.
> 🐛(project) fix NPM packages publication in the CI

- docs/index.md
This link serves no purpose. Removed it.
> 🐛(docs) fix home logo broken link

- Makefile
- docker-compose.yml
- src/api/core/pyproject.toml
- src/api/plugins/video/tests/test_api.py
- src/api/plugins/video/tests/test_indicators.py
We recently switched the project to Ralph 4 and some configuration are not fully compatible.
> Fix Ralph 4 integration

- bin/seed_experience_index.py
- src/api/core/warren/tests/fixtures/app.py
- src/api/core/warren/tests/xi/client/test_client.py
- src/api/core/warren/tests/xi/client/test_crud_experience.py
- src/api/core/warren/tests/xi/client/test_crud_relation.py
- src/api/core/warren/tests/xi/indexers/moodle/test_etl.py
- src/api/core/warren/xi/client.py
- src/api/core/warren/xi/indexers/moodle/etl.py
- src/api/core/warren/xi/routers/experiences.py
- src/api/core/warren/xi/routers/relations.py
- src/api/core/warren/xi/schema.py
A suite of various improvements around the XI.
> Improve XI API and client

- CHANGELOG.md
Preparing the first release of Warren distribution.
As Warren APIs are not stable yet, we will be releasing as major version zero.
- Implement base view filters: date/times
- Implement base plugin architecture
- Bootstrap base backend boilerplate
- Implement video views endpoint
- Bootstrap base frontend boilerplate using turborepo
- Run ralph in the docker compose
- Add the LRS backend
- Switch the video view plugin from an elasticsearch to a LRS backend
- Remove the elasticsearch backend
- Add the LTI django application
- Rename the API directory to a more descriptive name.
- Add a select and date range picker to the web dashboard.
- Implement video downloads endpoint
- Rename video_uuid to follow xAPI semantic
- Use concise names in indicator and models
- Refactor the LRS client to be …
> 🔖(minor) prepare 0.1.0 distribution release

- docker-compose.yml
- src/api/core/pyproject.toml
- src/api/core/warren/factories/base.py
- src/api/plugins/video/warren_video/factories.py
Ralph 4.2.0 has been recently released. Useful for the following fix on the LRS:
Fix querying on activity when LRS contains statements with an object lacking
a objectType attribute.
> ⬆️(project) upgrade Ralph dependency version

- src/frontend/.changeset/shaggy-cats-wait.md
- src/frontend/packages/core/CHANGELOG.md
- src/frontend/packages/core/package.json
- src/frontend/packages/video/CHANGELOG.md
- src/frontend/packages/video/package.json
- Export types in build package
> 🔖(frontend:patch) bump core release to 0.1.2

- src/app/apps/development/templates/development/lti_request.html
- src/app/apps/development/templates/development/lti_select.html
- src/app/apps/development/tests.py
- src/app/apps/development/urls.py
- src/app/apps/development/views.py
A development view for sending LTI requests already exists, but there was no development view for the LTI select page.
Adding the missing view.
> 🔨(project) add development view for lti select page

- CHANGELOG.md
- src/api/core/warren/__init__.py
- src/app/version.json
- src/app/warren/__init__.py
Added:
- Add development view for lti select page
> 🔖(patch) prepare 0.3.1 distribution release

- src/api/core/warren/models.py
- src/api/core/warren/tests/test_utils.py
- src/frontend/yarn.lock
Update LTI roles model to handle additional roles from Moodle LTI launch
requests, not covered by LTIRoles
> 🐛(api) fix lti roles model

- CHANGELOG.md
- src/api/core/warren/__init__.py
- src/app/version.json
- src/app/warren/__init__.py
- Fix LTI roles model to handle additional roles from Moodle LTI launch requests
> 🔖(patch) prepare 0.3.2 distribution release

- docs/Dockerfile
- src/api/Dockerfile
- src/app/Dockerfile
- src/frontend/Dockerfile
Since a recent version of Docker, many warnings are raised at build time from the Dockerfiles.
Fixing them.
> 🚨(project) resolve dockerfile build warnings

- CHANGELOG.md
- src/api/core/warren/__init__.py
- src/app/version.json
- src/app/warren/__init__.py
- [xi] Make timeout of requests to Moodle configurable
- [xi] Change default timeout of requests to Moodle from 5s to 60s
> 🔖(minor) prepare 0.5.0 distribution release

- .circleci/config.yml
- docker-compose.yml
As we want to update our postgres server to version 16, we use it locally and in our CI as well.
> ⬆️(backend) update postgres to version 16
